FILENAME=./StructureDumper.py

test:
	python3 -m unittest

test_extraction:
	python3 -m unittest tests.TestExtraction

test_comments:
	python3 -m unittest tests.TestCommentsRemover

run:
	$(FILENAME) pa_helpers.h sink_info_sub_
